version: "2"

services:

### Applications Code Container #############################

    applications:
      volumes:
        - ${APPLICATION}:/var/www
        - ${APPLICATION}../uploads:/var/www/public/uploads
        - ${APPLICATION}../storage:/var/www/storage